[package]
authors       = ["Sampo Kivistö, havunen"]
description   = "Rs Html Parser"
documentation = "https://github.com/Havunen/rs_html_parser"
edition       = "2021"
license       = "MIT"
name          = "rs_html_parser"
repository    = "https://github.com/Havunen/rs_html_parser.git"
version       = "0.0.1"

[lib]
bench = false

[dependencies]
rs_html_parser_nodes = { path = "../rs_html_parser_nodes" }
rs_html_parser_tokens = { path = "../rs_html_parser_tokens" }
rs_html_parser_tokenizer = { path = "../rs_html_parser_tokenizer" }

[dev-dependencies]
insta = {version = "1.34.0"}

